CURRENT_FOLDER_PATH = pwd()
CODE_SIENA_DATA_FOLDER_PATH = joinpath(CURRENT_FOLDER_PATH, "code Sienna data")
DATA_FOR_SIMULATION_FOLDER_PATH = joinpath(CODE_SIENA_DATA_FOLDER_PATH, "Data for simulation")
ADDITIONAL_DATA_FOLDER_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "additional_data")
COST_DATA_FOLDER_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "cost data")

DEMAND_DATA_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "demand_pdf_ver_diur.csv")
DEMAND_TS_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "demand_ts.csv")

#GENERATOR_DATA_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "resources.csv")
GENERATOR_DATA_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "resources1.csv")
GENERATION_TS_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "resources_ts.csv")

STORAGE_DATA_FILE_PATH = joinpath(DATA_FOR_SIMULATION_FOLDER_PATH, "storage_units.csv")

COST_MAP_FILE_PATH = joinpath(COST_DATA_FOLDER_PATH, "cost_map.csv")

